### ISSUE TITLE
Alternative to Nashorn

### ISSUE THREAD

**Issue by pmihalcin** [sdeleuze/spring-react-isomorphic#8]
Hi @sdeleuze 
Thanks a lot for this nice example.

Given the fact that Nashorn is deprecated: http://openjdk.java.net/jeps/335 (JEP 335: Deprecate the Nashorn JavaScript Engine).

Are you aware of any alternatives to Nashorn?

**Comment by danthe1st** [comment]
Graalvm?

**Comment by sdeleuze** [comment]
Yeah GraalVM JS support is the alternative.

**Comment by swaechter** [comment]
In case you rely on Node.js modules for rendering: Be aware of the design choices: https://github.com/graalvm/graaljs/issues/2
